spring.application.name=AprendiendoSpringSecurity

spring.security.user.name=victor
spring.security.user.password=1234

# CONFIGURACIONES DE BASE DE DATOS
spring.datasource.url=jdbc:mysql://localhost:3306/securitydb
spring.datasource.username=root
spring.datasource.password=sqlroot

# La Ubicación del Driver de sql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Este es el dialecto con el que hablamos con SQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Esto es para que en consola nos muestre las query sql que ejecuta JPA
spring.jpa.show-sql=true

# Con esto habilitamos que JPA cree las tablas a partir de nuestros entities
spring.jpa.hibernate.ddl-auto=create
