spring.application.name=AprendiendoSpringSecurity

spring.security.user.name=victor
spring.security.user.password=1234

# CONFIGURACIONES DE BASE DE DATOS
spring.datasource.url=jdbc:mysql://localhost:3306/securitydb
spring.datasource.username=root
spring.datasource.password=sqlroot

# La Ubicación del Driver de sql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Este es el dialecto con el que hablamos con SQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Esto es para que en consola nos muestre las query sql que ejecuta JPA
spring.jpa.show-sql=true

# Con esto habilitamos que JPA cree las tablas a partir de nuestros entities
spring.jpa.hibernate.ddl-auto=create

# JWT
# Esta es la clave con la que se firman los tokens
# El tiempo de expiración es en milisegundos, aquí tengo puesto 1 día
jwt.secret.key = b016bf86b3ab6ed1684bbd7a80fc6772d2c81ab1cbb7e23d9d78bbdbac675c9f
jwt.time.expiration = 86400000